<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Builder\Senac.ADS.PPFA.DesignPattern.Builder.csproj" />
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Decorator.Annotations\Senac.ADS.PPFA.DesignPattern.Decorator.Annotations.csproj" />
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Decorator\Senac.ADS.PPFA.DesignPattern.Decorator.csproj" />
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Facade\Senac.ADS.PPFA.DesignPattern.Facade.csproj" />
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Factory\Senac.ADS.PPFA.DesignPattern.Factory.csproj" />
    <ProjectReference Include="..\Senac.ADS.PPFA.DesignPattern.Singleton\Senac.ADS.PPFA.DesignPattern.Singleton.csproj" />
  </ItemGroup>

</Project>